SELECT 
    A.AUTHOR_ID AS AUTHOR_ID, 
    A.AUTHOR_NAME AS AUTHOR_NAME, 
    B.CATEGORY AS CATEGORY, 
    SUM(B.PRICE * BS.SALES) AS TOTAL_SALES
FROM BOOK B
JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN (
    SELECT BOOK_ID, SALES
    FROM BOOK_SALES
    WHERE SALES_DATE >= '2022-01-01' AND SALES_DATE < '2022-02-01'
) BS
ON B.BOOK_ID = BS.BOOK_ID
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC