SELECT 
    CRCC.CAR_ID AS CAR_ID, 
    CRCC.CAR_TYPE AS CAR_TYPE, 
    ROUND(CRCC.DAILY_FEE*30*0.01*(100-CRCDP.DISCOUNT_RATE)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CRCC
    JOIN (
        SELECT CAR_TYPE, DISCOUNT_RATE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE 
            CAR_TYPE IN ('세단', 'SUV') AND DURATION_TYPE = '30일 이상'
    ) CRCDP
    ON CRCC.CAR_TYPE = CRCDP.CAR_TYPE
WHERE 
    CRCC.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE 
            END_DATE >= '2022-11-01' AND START_DATE <= '2022-12-01'
    ) 
    AND ROUND(CRCC.DAILY_FEE*30*0.01*(100-CRCDP.DISCOUNT_RATE)) >= 500000 
    AND ROUND(CRCC.DAILY_FEE*30*0.01*(100-CRCDP.DISCOUNT_RATE)) < 2000000
ORDER BY ROUND(CRCC.DAILY_FEE*30*0.01*(100-CRCDP.DISCOUNT_RATE)) DESC, CAR_TYPE, CAR_ID DESC