SELECT 
    INS.ANIMAL_ID,
    INS.ANIMAL_TYPE,
    INS.NAME
FROM ANIMAL_INS INS
JOIN ANIMAL_OUTS OUTS
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE 
    (INS.SEX_UPON_INTAKE = 'Intact Male' or INS.SEX_UPON_INTAKE = 'Intact Female')
    AND 
    (OUTS.SEX_UPON_OUTCOME = 'Spayed Male' OR OUTS.SEX_UPON_OUTCOME = 'Neutered Male'
    OR
    OUTS.SEX_UPON_OUTCOME = 'Spayed Female' OR OUTS.SEX_UPON_OUTCOME = 'Neutered Female')
    
