SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, FP.PRICE * FO.TOT AS TOTAL_SALES
FROM FOOD_PRODUCT FP
JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS TOT
    FROM FOOD_ORDER 
    WHERE '2022-05-01' <= PRODUCE_DATE AND PRODUCE_DATE <= '2022-05-31'
    GROUP BY PRODUCT_ID
) FO
ON FP.PRODUCT_ID = FO.PRODUCT_ID 
ORDER BY FP.PRICE * FO.TOT DESC, FP.PRODUCT_ID 
