SELECT 
    CRCRH.HISTORY_ID,
    ROUND((DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE)+1) * CRCC.DAILY_FEE * (1 - 
    CASE
        WHEN DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE)+1 >= 90
        THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE='트럭' AND DURATION_TYPE='90일 이상')
        WHEN DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE)+1 >= 30
        THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE='트럭' AND DURATION_TYPE='30일 이상')
        WHEN DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE)+1 >= 7
        THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE='트럭' AND DURATION_TYPE='7일 이상')                                            
        ELSE 0
    END / 100)) AS FEE                                                  
    
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
JOIN CAR_RENTAL_COMPANY_CAR CRCC
ON CRCRH.CAR_ID = CRCC.CAR_ID
WHERE CRCC.CAR_TYPE = '트럭'
ORDER BY FEE DESC, CRCRH.HISTORY_ID DESC

