# SELECT
#     HOUR(DATETIME) AS HOUR,
#     COUNT(*) AS COUNT
# FROM ANIMAL_OUTS
# GROUP BY HOUR(DATETIME)
# ORDER BY HOUR

WITH RECURSIVE NumberTable AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM NumberTable
    WHERE HOUR < 23
)

SELECT 
    HOUR,
    (SELECT COUNT(*) FROM ANIMAL_OUTS WHERE HOUR(DATETIME) = HOUR) AS COUNT
FROM NumberTable;