SELECT 
    MP.MEMBER_NAME,
    RR.REVIEW_TEXT,
    DATE_FORMAT(RR.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE MP
JOIN REST_REVIEW RR
ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE MP.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM (
        SELECT MEMBER_ID, COUNT(*) AS COUNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
    ) P
    WHERE COUNT = (
        SELECT MAX(COUNT)
        FROM(
        SELECT MEMBER_ID, COUNT(*) AS COUNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID) TMP
    )
)
ORDER BY RR.REVIEW_DATE, RR.REVIEW_TEXT
